name: Publish Package to npm

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # v5
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Setup Bun
        # v2.2.0
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6
        with:
          bun-version-file: ".bun-version"

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Run checks (typecheck, lint, format)
        run: bun run check

      - name: Publish to npm
        run: bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
